[package]
name = "plp-mocks"
version = "0.1.0"
edition = "2024"
authors = ["Falldot <fe.offep@gmail.com>"]
readme = "README.md"
description = "TODO"
license = "MIT"
homepage = "https://github.com/plp-lang/mocks"
repository = "https://github.com/plp-lang/mocks"
categories = [
    "development-tools::testing"
]
keywords = [
    "testing",
    "mocks",
]

[lints.rust]

[lints.clippy]
complexity = { level = "deny", priority = -1 }
suspicious =  { level = "deny", priority = -1 }
correctness =  { level = "deny", priority = -1 }

perf =  { level = "warn", priority = -1 }
cargo =  { level = "warn", priority = -1 }
style =  { level = "warn", priority = -1 }
nursery =  { level = "warn", priority = -1 }
pedantic =  { level = "warn", priority = -1 }

multiple_crate_versions = "allow"

[dependencies]
thiserror = "2.0.18"
base64 = "0.22.1"
hex = "0.4.3"
clap = { version = "4.6.1", features = ["derive", "env"] }
serde = { version = "1.0.228" }
async-trait = "0.1.89"
log = { version = "0.4.32", features = ["serde"] }
tokio = { version = "1.52.3", features = ["full"] }
tracing = { version = "0.1.44", features = ["attributes"] }
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
tower = { version = "0.5.3", features = ["util"] }
tower-http = { version = "0.6", features = ["trace"] }
quick-xml = { version = "0.40.1", features = ["serialize"] }
fake = { version = "5.1.0", features = ["derive"] }
axum = "0.8.9"
sqlx = { version = "0.9.0", features = ["runtime-tokio", "sqlite"] }
cookie = "0.18.1"
chrono = { version = "0.4.45", features = ["serde"] }
